[build]
  # Directory to publish (same as dist folder from Vite)
  publish = "dist"
  
  # Build command - força um build limpo
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build:netlify"
  
  # Ignora cache para forçar build
  ignore = "false"

[build.environment]
  NODE_VERSION = "18"

# SPA redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Progressive Web App support
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
